
variable "cloud_token" {
  type    = string
  default = "${env("VAGRANT_CLOUD_TOKEN")}"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

locals {
  build_id = "win2019-${local.timestamp}"
  version  = "1.0.${local.timestamp}"
}

source "virtualbox-iso" "autogenerated_1" {
  boot_wait            = "10s"
  communicator         = "ssh"
  disk_size            = "40440"
  floppy_files         = ["floppy"]
  cd_files             = ["cd/*"]
  cd_label             = "cidata"
  guest_additions_mode = "disable"
  guest_os_type        = "Windows10_64"
  headless             = "false"
  iso_checksum         = "549bca46c055157291be6c22a3aaaed8330e78ef4382c99ee82c896426a1cee1"
  //iso_checksum_type    = "sha256"
  iso_url              = "https://software-download.microsoft.com/download/pr/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
  output_directory     = "./out-${local.build_id}"
  post_shutdown_delay  = "5s" // 5m change nothing about Could not find a controller named 'Floppy Controller'
  shutdown_command     = "A:/shutdown.cmd"
  shutdown_timeout     = "10m"
  ssh_password         = "vagrant"
  // Basic installation can have 15m timeout
  // MSSQL installation has a 20m timeout
  // SQL Management Studio can take maybe 10m
  // Optimal is probably 45m
  // Sometime VIM take very long time to download 10m
  ssh_timeout          = "60m"
  ssh_username         = "vagrant"
  vboxmanage           = [
	["modifyvm", "{{ .Name }}", "--memory", "4096"], ["modifyvm", "{{ .Name }}", "--cpus", "2"]
// ["storagectl", "{{ .Name }}", "--add", "floppy", "--controller", "I82078", "--name", "Floppy Controller"]
  ]
  vm_name              = "${local.build_id}"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  post-processors {
    post-processor "vagrant" {
      compression_level    = 9
      output               = "${local.build_id}_{{ .BuildName }}_{{ .Provider }}.box"
      vagrantfile_template = "Vagrantfile.tpl"
    }
    // post-processor "vagrant-cloud" {
    //   access_token        = "${var.cloud_token}"
    //   box_tag             = "mcree/win2019"
    //   version             = "${local.version}"
    //   version_description = "See: https://github.com/mcree/vagrant-windows-server-2019"
    // }
  }
}
